Bump rubocop's TargetRubyVersion to 2.4
From CircleCI:

```
bundle exec rubocop -D

Error: Unsupported Ruby version 2.1 found in `TargetRubyVersion`
parameter (in .rubocop.yml). 2.1-compatible analysis was dropped after
version 0.58.
Supported versions: 2.2, 2.3, 2.4, 2.5
```

We use 2.4, so using that.