Add a ssh_command_generator config for running a custom ssh generator command (#169)
Tested with and without `ssh_command_generator` in the config

* Without
```
The host might be broken or your SSH access is not working properly
Try doing

    TERM=screen.xterm-256color SSH_AUTH_SOCK=/tmp/cloud-ssh-nish-agent /bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22  -T -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=60 -v centos@<redacted_host>

to see if ssh connection is good.

If ssh works, add '-v' key to taste-tester to see the list of commands it's
trying to execute, and try to run them manually on destination host
```

* With direct host
```
SSH returned error while connecting to centos@<redacted_host>
The host might be broken or your SSH access is not working properly
Try running the following command to see if ssh is good:

    TERM=screen.xterm-256color SSH_AUTH_SOCK=/tmp/cloud-ssh-nish-agent /bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -o ServerAliveInterval=60 -o ServerAliveCountMax=5 -o 'ProxyCommand=<redacted> %h %p' centos@<redacted_host> -v


The above command was generated, and it may be useful to run the generator directly instead:

    mock_command_generator --user centos --get-command

If ssh works, add '-v' key to taste-tester to see the list of commands it's
trying to execute, and try to run them manually on destination host
```

* With jumphost
```
SSH returned error while connecting to centos@bad_host
The host might be broken or your SSH access is not working properly
Try running the following command to see if ssh is good:

    TERM=screen.xterm-256color SSH_AUTH_SOCK=/tmp/cloud-ssh-nish-agent /bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22 -o ServerAliveInterval=60 -o ServerAliveCountMax=5 -o 'ProxyCommand=/bin/ssh -W %h:%p -o "ProxyCommand=<redacted> %%h %%p" centos@<jump_host>' centos@bad_host -v


The above command was generated, and it may be useful to run the generator directly instead:

    mock_command_generator -J <jump_host> bad_host --user centos --get-command

If ssh works, add '-v' key to taste-tester to see the list of commands it's
trying to execute, and try to run them manually on destination host
```

* Test with --use-ssh-tunnels and generator code
```
$ taste-tester <redacted_options > -J <redacted_jumphost> -s <redacted_host> --use-ssh-tunnels --yes
Loading plugin at /etc/taste-tester/hooks/cloud-hooks.rb
Using /home/nish/opsfiles
Uploading cookbooks: [fb_chef_client]
Taste-testing on <redacted_host>
Waiting for prod chef runs to complete on <redacted_host>
.
.
The host is now in testing mode. You will need to run chefctl (or soloctl
as appropriate) manually while the server is in testing mode.
.
.
```
* Test with --no-use-ssh-tunnels and generator code
```
$ taste-tester <redacted_options> -J <redacted_jumphost> -s <redacted_host> --no-use-ssh-tunnels --yes
Loading plugin at /etc/taste-tester/hooks/cloud-hooks.rb
Using /home/nish/opsfiles
Uploading cookbooks: [fb_chef_client]
Taste-testing on <redacted_host>
Waiting for prod chef runs to complete on <redacted_host>
.
.
The host is now in testing mode. You will need to run chefctl (or soloctl
as appropriate) manually while the server is in testing mode.
.
.
```

* Sanity test with tunnels without generator code
```
$ taste-tester --solo <example> test --use-ssh-tunnels --user centos -s <redacted_host> 
Taste-tester type: fb-chef-solo[<example>]
Loading plugin at /etc/taste-tester/hooks/<example>.rb
Set ["<example>"] to test mode? [y/N] y
Using /home/nish/opsfiles
Nothing to upload!
Taste-testing on <example>
Waiting for prod chef runs to complete on <example>
.
The host is now in testing mode. You will need to run chefctl (or soloctl
as appropriate) manually while the server is in testing mode. See..
```

* Test failure with bullshit args in the config
```
$ taste-tester <redacted_options> -J <redacted_jumphost> -s <redacted_host> --skip-repo-checks --no-use-ssh-tunnels --yes
Loading plugin at /etc/taste-tester/hooks/cloud-hooks.rb
Using /home/nish/opsfiles
Uploading cookbooks: [fb_chef_client]
Taste-testing on <redacted_host>
The generator command: <redacted_gen_cmd> --user centos --get-command-nish failed during execution
Expected process to exit with [0], but received '1'
---- Begin output of <redacted_gen_cmd> --user centos --get-command-nish ----
STDOUT:
STDERR: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:340: warning: Insecure world writable dir /var/www/scripts in PATH, mode 040777
Usage: <redacted_gen_cmd>
Try '<redacted_gen_cmd> -h' for help.

Error: no such option: --get-command-nish
---- End output of <redacted_gen_cmd>l --user centos --get-command-nish ----
Ran <redacted_gen_cmd> --user centos --get-command-nish returned 1
```